version: '3'

services:
  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - wp

  wp:
    build: ./wp
    restart: unless-stopped
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER:
      WORDPRESS_DB_PASSWORD:
      WORDPRESS_DB_NAME:

  db:
    image: mysql:8.1
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 10000:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db

volumes:
  db:
