version: '3.1'

services:
  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - wp:/var/www/html
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
    depends_on:
      - wp
      - certbot

  wp:
    build: ./wp
    restart: unless-stopped
    volumes:
      - wp:/var/www/html
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST:
      WORDPRESS_DB_USER:
      WORDPRESS_DB_PASSWORD:
      WORDPRESS_DB_NAME:

  db:
    image: mysql:8.1
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
      - wp:/var/www/html
    command: certonly --staging --webroot --webroot-path=/var/www/html -d ${LE_DOMAIN} --email ${LE_EMAIL} --agree-tos --no-eff-email
    depends_on:
      - wp
    environment:
      LE_EMAIL:
      LE_DOMAIN:

volumes:
  wp:
  db:
