version: '3.1'

services:
  nginx:
    image: nginx:1.25
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - wp:/var/www/html
      - ./nginx/wp.conf:/etc/nginx/conf.d/wp.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - wp

  wp:
    build: ./wp
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST:
      WORDPRESS_DB_USER:
      WORDPRESS_DB_PASSWORD:
      WORDPRESS_DB_NAME:
    volumes:
      - wp:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.1
    restart: unless-stopped
    environment:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    volumes:
      - db:/var/lib/mysql
  
volumes:
  wp:
  db: