version: '3.1'

services:
  nginx:
    image: nginx:1.25
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - wp:/var/www/html
      - ./nginx/:/etc/nginx/:ro
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - wp
      - db

  certbot:
    image: certbot/certbot
    volumes:
      - letsencrypt:/etc/letsencrypt
      - wp:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email ${EMAIL} --agree-tos --no-eff-email -d ${DOMAIN}
    depends_on:
      - nginx
      - wp
      - db

  wp:
    build: ./wp
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST:
      WORDPRESS_DB_USER:
      WORDPRESS_DB_PASSWORD:
      WORDPRESS_DB_NAME:
    volumes:
      - wp:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.1
    restart: unless-stopped
    environment:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    volumes:
      - db:/var/lib/mysql
  
volumes:
  wp:
  db:
  letsencrypt: